# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app2.py .

# Install any dependencies needed for your script
RUN pip install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation

# Define environment variables
# ENV OTEL_RESOURCE_ATTRIBUTES="service.name=service"
# ENV OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"

# Run the Python script when the container starts
CMD ["python", "app2.py"]
