# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app4.py .

# Install OpenTelemetry SDK and exporter
#RUN pip install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp
RUN pip install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation

# Run the Python script when the container starts
CMD ["python", "app4.py"]
#CMD ["opentelemetry-instrument", "python", "app4.py"] 
